import fulfillmentInbound_v0 from './versions/fulfillment_inbound/fulfillmentInbound_v0';
import fulfillmentInbound_2024_03_20 from './versions/fulfillment_inbound/fulfillmentInbound_2024-03-20';

export default {
  fulfillmentInbound: {
    __versions: ['v0', '2024-03-20'],
    __operations: [
      'getPrepInstructions',
      'getLabels',
      'getBillOfLading',
      'getShipments',
      'getShipmentItemsByShipmentId',
      'getShipmentItems',
      'listInboundPlans',
      'createInboundPlan',
      'getInboundPlan',
      'listInboundPlanBoxes',
      'cancelInboundPlan',
      'listInboundPlanItems',
      'updateInboundPlanName',
      'listPackingGroupBoxes',
      'listPackingGroupItems',
      'setPackingInformation',
      'listPackingOptions',
      'generatePackingOptions',
      'confirmPackingOption',
      'listInboundPlanPallets',
      'listPlacementOptions',
      'generatePlacementOptions',
      'confirmPlacementOption',
      'getShipment',
      'listShipmentBoxes',
      'listShipmentContentUpdatePreviews',
      'generateShipmentContentUpdatePreviews',
      'getShipmentContentUpdatePreview',
      'confirmShipmentContentUpdatePreview',
      'getDeliveryChallanDocument',
      'listDeliveryWindowOptions',
      'generateDeliveryWindowOptions',
      'confirmDeliveryWindowOptions',
      'listShipmentItems',
      'updateShipmentName',
      'listShipmentPallets',
      'cancelSelfShipAppointment',
      'getSelfShipAppointmentSlots',
      'generateSelfShipAppointmentSlots',
      'scheduleSelfShipAppointment',
      'updateShipmentSourceAddress',
      'updateShipmentTrackingDetails',
      'listTransportationOptions',
      'generateTransportationOptions',
      'confirmTransportationOptions',
      'updateItemComplianceDetails',
      'createMarketplaceItemLabels',
      'getInboundOperationStatus',
      'listPrepDetails',
      'setPrepDetails'
    ],
    ...fulfillmentInbound_v0,
    ...fulfillmentInbound_2024_03_20
  }
};
